exports.scanTables = [
    {lang: 'ENG', category: 1, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 1, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 1, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 1, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 1, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 1, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 2, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 2, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 2, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 2, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 2, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 2, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 3, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 3, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 3, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 3, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 3, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 3, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 4, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 4, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 4, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 4, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 4, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 4, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 5, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 5, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 5, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 5, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 5, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 5, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 6, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 6, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 6, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 6, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 6, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 6, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 7, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 7, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 7, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 7, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 7, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 7, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 8, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 8, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 8, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 8, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 8, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 8, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 9, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 9, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 9, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 9, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 9, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 9, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 10, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 10, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 10, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 10, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 10, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 10, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 11, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 11, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 11, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 11, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 11, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 11, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 12, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 12, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 12, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 12, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 12, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 12, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 13, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 13, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 13, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 13, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 13, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 13, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 14, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 14, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 14, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 14, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 14, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 14, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 15, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 15, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 15, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 15, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 15, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 15, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 16, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 16, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 16, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 16, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 16, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 16, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 17, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 17, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 17, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 17, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 17, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 17, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 18, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 18, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 18, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 18, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 18, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 18, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 19, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 19, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 19, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 19, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 19, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 19, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 20, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 20, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 20, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 20, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 20, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 20, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 21, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 21, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 21, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 21, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 21, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 21, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 22, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 22, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 22, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 22, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 22, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 22, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 23, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 23, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 23, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 23, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 23, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 23, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 24, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 24, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 24, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 24, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 24, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 24, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 25, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 25, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 25, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 25, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 25, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 25, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 26, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 26, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 26, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 26, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 26, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 26, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 27, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 27, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 27, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 27, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 27, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 27, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 28, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 28, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 28, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 28, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 28, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 28, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 29, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 29, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 29, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 29, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 29, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 29, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 32, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 32, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 32, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 32, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 32, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 32, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 33, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 33, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 33, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 33, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 33, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 33, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 34, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 34, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 34, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 34, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 34, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 34, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 36, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 36, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 36, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 36, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 36, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 36, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 37, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 37, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 37, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 37, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 37, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 37, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 38, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 38, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 38, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 38, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 38, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 38, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 39, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 39, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 39, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 39, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 39, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 39, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 40, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 40, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 40, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 40, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 40, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 40, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 41, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 41, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 41, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 41, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 41, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 41, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 42, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 42, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 42, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 42, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 42, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 42, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 43, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 43, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 43, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 43, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 43, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 43, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 45, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 45, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 45, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 45, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 45, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 45, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 46, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 46, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 46, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 46, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 46, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 46, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 47, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 47, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 47, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 47, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 47, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 47, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 48, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 48, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 48, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 48, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 48, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 48, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 49, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 49, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 49, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 49, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 49, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 49, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 50, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 50, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 50, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 50, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 50, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 50, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 51, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 51, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 51, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 51, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 51, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 51, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 53, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 53, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 53, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 53, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 53, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 53, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 54, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 54, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 54, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 54, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 54, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 54, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 55, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 55, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 55, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 55, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 55, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 55, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 56, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 56, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 56, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 56, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 56, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 56, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 57, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 57, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 57, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 57, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 57, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 57, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 58, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 58, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 58, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 58, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 58, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 58, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 59, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 59, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 59, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 59, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 59, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 59, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 60, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 60, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 60, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 60, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 60, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 60, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 61, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 61, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 61, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 61, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 61, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 61, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 62, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 62, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 62, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 62, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 62, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 62, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 63, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 63, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 63, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 63, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 63, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 63, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 64, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 64, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 64, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 64, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 64, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 64, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 65, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 65, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 65, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 65, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 65, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 65, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 66, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 66, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 66, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 66, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 66, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 66, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 67, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 67, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 67, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 67, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 67, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 67, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 69, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 69, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 69, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 69, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 69, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 69, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 70, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 70, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 70, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 70, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 70, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 70, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 71, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 71, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 71, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 71, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 71, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 71, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 72, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 72, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 72, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 72, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 72, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 72, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 74, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 74, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 74, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 74, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 74, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 74, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 76, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 76, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 76, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 76, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 76, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 76, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 77, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 77, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 77, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 77, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 77, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 77, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 78, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 78, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 78, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 78, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 78, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 78, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 80, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 80, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 80, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 80, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 80, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 80, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 96, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 96, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 96, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 96, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 96, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 96, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 97, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 97, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 97, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 97, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 97, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 97, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'ENG', category: 98, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'ENG', category: 98, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'ENG', category: 98, price_from: 100, price_to: 150, done: 0, count: null},
    {lang: 'POL', category: 98, price_from: 0, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 98, price_from: 50, price_to: 100, done: 0, count: null},
    {lang: 'POL', category: 98, price_from: 100, price_to: 150, done: 0, count: null}       
]

const categories = [
    {id: 1, name: 'Inne'},
    {id: 2, name: 'Literatura piękna'},
    {id: 3, name: 'Hobby'},
    {id: 4, name: 'Literatura faktu'},
    {id: 5, name: 'Kalendarze'},
    {id: 6, name: 'Nauka'},
    {id: 7, name: 'Podręczniki'},
    {id: 8, name: 'Sztuka'},
    {id: 9, name: 'Sport'},
    {id: 10, name: 'Religia'},
    {id: 11, name: 'Encyklopedie'},
    {id: 12, name: 'Zdrowie'},
    {id: 13, name: 'AudioBooki'},
    {id: 14, name: 'Biologia i przyroda'},
    {id: 15, name: 'Chemia'},
    {id: 16, name: 'Ekonomia i biznes'},
    {id: 17, name: 'Fizyka'},
    {id: 18, name: 'Geografia'},
    {id: 19, name: 'Matematyka'},
    {id: 20, name: 'Filozofia'},
    {id: 21, name: 'Historia'},
    {id: 22, name: 'Językoznawstwo'},
    {id: 23, name: 'Kultura. Etnografia'},
    {id: 24, name: 'Literaturoznawstwo'},
    {id: 25, name: 'Pedagogika i oświata'},
    {id: 26, name: 'Polityka'},
    {id: 27, name: 'Prawo i administracja'},
    {id: 28, name: 'Psychologia'},
    {id: 29, name: 'Socjologia i społeczeństwo'},
    {id: 32, name: 'Fantastyka'},
    {id: 33, name: 'Historyczna'},
    {id: 34, name: 'Przygodowa'},
    {id: 36, name: 'Satyryczna'},
    {id: 37, name: 'Sensacyjna'},
    {id: 38, name: 'Obyczajowa'},
    {id: 39, name: 'Poezja'},
    {id: 40, name: 'Dramat'},
    {id: 41, name: 'Dziecięca'},
    {id: 42, name: 'Turystyka'},
    {id: 43, name: 'Atlasy i mapy'},
    {id: 45, name: 'Przewodniki'},
    {id: 46, name: 'Dom'},
    {id: 47, name: 'Ogród'},
    {id: 48, name: 'Zwierzęta'},
    {id: 49, name: 'Kolekcjonerstwo'},
    {id: 50, name: 'Fotografia'},
    {id: 51, name: 'Architektura'},
    {id: 53, name: 'Muzyka'},
    {id: 54, name: 'Poradniki'},
    {id: 55, name: 'Informatyka'},
    {id: 56, name: 'Programowanie'},
    {id: 57, name: 'Bazy danych'},
    {id: 58, name: 'Bezpieczeństwo'},
    {id: 59, name: 'Sieci komputerowe'},
    {id: 60, name: 'Internet'},
    {id: 61, name: 'Grafika komputerowa'},
    {id: 62, name: 'Sprzęt komputerowy'},
    {id: 63, name: 'Technologie'},
    {id: 64, name: 'Archeologia'},
    {id: 65, name: 'Romanse'},
    {id: 66, name: 'Dla dorosłych'},
    {id: 67, name: 'Komiksy'},
    {id: 69, name: 'CD, DVD, Video'},
    {id: 70, name: 'CD-Audio'},
    {id: 71, name: 'Video'},
    {id: 72, name: 'DVD'},
    {id: 74, name: 'Oprogramowanie'},
    {id: 76, name: 'Medycyna'},
    {id: 77, name: 'Czasopisma'},
    {id: 78, name: 'Słowniki'},
    {id: 80, name: 'Muzyka CD'},
    {id: 96, name: 'Książkowe Klimaty'},
    {id: 97, name: 'Zabawki'},
    {id: 98, name: 'Puzzle, gry'}
]

exports.getCategoryName = (catid) => {
    try {
        return categories[getCategoryIndex(catid)].name;
    } catch (e) {
        return "Error. Category id ["+catid+"] not found";
    }
}

const getCategoryIndex = (id) => {
    let index = categories.findIndex(i => 1*i.id === 1*id);
    if (index!==-1) {
        return index;
    } else {
        throw "Index of ["+id+"] not found in array";
    }
}

exports.scanTables2 = [
//2	Literatura piękna
    // {lang: 'ENG', category: 2, price_from: 9, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 2, price_from: 9, price_to: 50, done: 0, count: null},
//8	Sztuka   
    {lang: 'ENG', category: 8, price_from: 9, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 8, price_from: 9, price_to: 50, done: 0, count: null},
//43	Atlasy i mapy
    {lang: 'ENG', category: 43, price_from: 9, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 43, price_from: 9, price_to: 50, done: 0, count: null},
//55	Informatyka
    {lang: 'ENG', category: 55, price_from: 9, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 55, price_from: 9, price_to: 50, done: 0, count: null},
//56	Programowanie
    {lang: 'ENG', category: 56, price_from: 9, price_to: 50, done: 0, count: null},
    {lang: 'POL', category: 56, price_from: 9, price_to: 50, done: 0, count: null}
]

exports.currentScan = 0;